# Generated by Django 4.2.6 on 2023-10-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
    ]
