# Generated by Django 4.2.6 on 2023-12-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_rename_answers_question_answer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_of_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
