# Generated by Django 4.2.6 on 2023-10-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='questions', to='tests.answer'),
        ),
    ]
